### ISSUE TITLE
Hosting on Github

### ISSUE THREAD

**Issue by BumbleFuzzz** [amethystnetwork-dev/Incognito#15]
### Comment

I have forked this, but I want to host this on github pages. How would I go about doing this?

**Comment by AsherSaenz** [comment]
As far as I am aware it doesn't work well with github pages.
A good site that runs this well is gitpod if the listed options are not working for you, that is currently what I use as a host for this.

**Comment by BumbleFuzzz** [comment]
> As far as I am aware it doesn't work well with github pages. A good site that runs this well is gitpod if the listed options are not working for you, that is currently what I use as a host for this.

dang they have it blocked

**Comment by AsherSaenz** [comment]
I would say look into disabling the extensions with something like this: https://github.com/AsherSaenz/ext-remover it helped me out so that I'm not being tracked fully so they don't know how to block what I'm on. But pretty much at this point look into alternative hosting sites until you get one to work. When you get one, don't share it with anyone else unless you can get their computer extensions disabled as well in order to preserve the site from being blocked

**Comment by NRZT555** [comment]
Github pages are not supported for incognito. You can deploy this to sites that are supported and not static host sites.

**Comment by mdoryammilwalrus** [comment]
Static hosts also include netifly and vercel. I do also see a bunch of vercel traffic on the insights page.
